name: No Local Training Guard

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Ежедневная проверка
    - cron: '0 0 * * *'

jobs:
  guard-no-local-train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pyyaml

    - name: Check ALLOW_LOCAL_TRAIN environment variable
      run: |
        echo "🔍 Проверка переменной окружения ALLOW_LOCAL_TRAIN..."

        # Проверка переменной окружения
        if [ "${{ secrets.ALLOW_LOCAL_TRAIN }}" = "true" ]; then
          echo "❌ ALLOW_LOCAL_TRAIN установлен в true!"
          echo "💡 Локальное обучение запрещено в этом проекте"
          echo "💡 Используйте внешние кластеры для обучения модели"
          exit 1
        fi

        if [ "${{ vars.ALLOW_LOCAL_TRAIN }}" = "true" ]; then
          echo "❌ ALLOW_LOCAL_TRAIN установлен в true в переменных репозитория!"
          exit 1
        fi

        echo "✅ ALLOW_LOCAL_TRAIN не установлен или установлен в false"

    - name: Check for local training code paths
      run: |
        echo "🔍 Поиск потенциальных путей локального обучения..."

        # Поиск ключевых слов, указывающих на локальное обучение
        forbidden_patterns=(
          "train.*local"
          "local.*train"
          "localhost.*train"
          "127.0.0.1.*train"
          "accelerate.*launch"
          "torchrun"
          "python.*train"
          "deepspeed.*--num_gpus"
          "CUDA_VISIBLE_DEVICES.*[0-9]"
        )

        exit_code=0

        for pattern in "${forbidden_patterns[@]}"; do
          if grep -r -i "$pattern" --include="*.py" --include="*.sh" --include="*.yaml" --include="*.yml" . > /dev/null; then
            echo "❌ Найден подозрительный паттерн: $pattern"
            exit_code=1
          fi
        done

        if [ $exit_code -eq 0 ]; then
          echo "✅ Подозрительные паттерны локального обучения не найдены"
        else
          echo "💡 Если это ложное срабатывание, добавьте комментарий в код"
          exit 1
        fi

    - name: Check training launcher for guards
      run: |
        echo "🔍 Проверка лаунчера обучения на наличие гвардов..."

        # Проверка существования файла лаунчера
        if [ ! -f "training/launcher.py" ]; then
          echo "❌ Файл training/launcher.py не найден"
          exit 1
        fi

        # Проверка наличия гварда в лаунчере
        if ! grep -q "ALLOW_LOCAL_TRAIN" training/launcher.py; then
          echo "❌ В лаунчере отсутствует проверка ALLOW_LOCAL_TRAIN"
          exit 1
        fi

        if ! grep -q "local.*train.*not.*allowed" training/launcher.py; then
          echo "❌ В лаунчере отсутствует сообщение об ошибке локального обучения"
          exit 1
        fi

        echo "✅ Лаунчер обучения содержит необходимые гварды"

    - name: Check Makefile for local training targets
      run: |
        echo "🔍 Проверка Makefile на цели локального обучения..."

        # Поиск целей обучения в Makefile
        if grep -q "^train:" Makefile; then
          echo "❌ Найдена цель train в Makefile"
          echo "💡 Удалите локальные цели обучения или добавьте гварды"
          exit 1
        fi

        if grep -q "accelerate.*launch" Makefile; then
          echo "❌ Найден accelerate launch в Makefile"
          exit 1
        fi

        echo "✅ Makefile не содержит локальных целей обучения"

    - name: Check CI workflows for local training
      run: |
        echo "🔍 Проверка CI workflow файлов на локальное обучение..."

        # Проверка всех .yml файлов в .github/
        if [ -d ".github" ]; then
          for workflow in .github/workflows/*.yml; do
            if [ -f "$workflow" ]; then
              if grep -q "train" "$workflow" && grep -q "run:" "$workflow"; then
                echo "⚠️  Найден потенциальный workflow с обучением: $(basename "$workflow")"
                # Не фейлим сразу, только предупреждаем
              fi
            fi
          done
        fi

        echo "✅ Проверка CI workflow завершена"

    - name: Verify external model guard is active
      run: |
        echo "🔍 Проверка активности гварда внешних моделей..."

        # Проверка существования файла гварда
        if [ ! -f "ci/guard_external_models.yml" ]; then
          echo "❌ Файл ci/guard_external_models.yml не найден"
          exit 1
        fi

        # Проверка актуальности списка запрещённых моделей
        forbidden_models=("gpt2" "llama" "mistral" "qwen" "phi" "gemma" "opt" "bloom" "falcon" "pythia")

        for model in "${forbidden_models[@]}"; do
          if ! grep -q "$model" ci/guard_external_models.yml; then
            echo "⚠️  Модель $model не найдена в списке запрещённых"
          fi
        done

        echo "✅ Гвард внешних моделей активен"

    - name: Generate no-local-train report
      run: |
        echo "📊 Генерация отчёта о статусе гварда локального обучения..."

        echo "
        # No Local Training Guard Report

        **Generated:** $(date)

        **Status:** ✅ ACTIVE

        **Checks performed:**
        - ✅ Environment variable check
        - ✅ Code pattern analysis
        - ✅ Training launcher guards
        - ✅ Makefile validation
        - ✅ External model guard verification

        **Recommendations:**
        - Keep ALLOW_LOCAL_TRAIN=false in production
        - Monitor for new training scripts
        - Regular CI/CD pipeline reviews

        **Project compliance:** Oracle850B-MoE (Own Architecture Only)
        " > no_local_train_report.md

        echo "✅ Отчёт о гварде локального обучения сгенерирован"

    - name: Upload report artifact
      uses: actions/upload-artifact@v3
      with:
        name: no-local-train-report
        path: no_local_train_report.md
