apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle850b-serving
  namespace: oracle850b
  labels:
    app: oracle850b
    component: serving
spec:
  replicas: {{ .Values.serving.replicas }}
  selector:
    matchLabels:
      app: oracle850b
      component: serving
  template:
    metadata:
      labels:
        app: oracle850b
        component: serving
    spec:
      serviceAccountName: oracle850b-serving
      containers:
      - name: oracle850b-serving
        image: {{ .Values.serving.image.repository }}:{{ .Values.serving.image.tag }}
        imagePullPolicy: {{ .Values.serving.image.pullPolicy }}
        command: ["python"]
        args: ["src/oracle/core/serve/app_fastapi.py"]
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: metrics
        resources:
          requests:
            memory: {{ .Values.serving.resources.requests.memory }}
            cpu: {{ .Values.serving.resources.requests.cpu }}
            nvidia.com/gpu: {{ .Values.serving.resources.requests.gpu }}
          limits:
            memory: {{ .Values.serving.resources.limits.memory }}
            cpu: {{ .Values.serving.resources.limits.cpu }}
            nvidia.com/gpu: {{ .Values.serving.resources.limits.gpu }}
        env:
        - name: MODEL_PATH
          value: "/app/checkpoints/oracle850b"
        - name: CUDA_VISIBLE_DEVICES
          value: "all"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: checkpoints-volume
          mountPath: /app/checkpoints
        - name: config-volume
          mountPath: /app/configs
      volumes:
      - name: checkpoints-volume
        persistentVolumeClaim:
          claimName: oracle850b-checkpoints
      - name: config-volume
        configMap:
          name: oracle850b-config
      nodeSelector:
        yandex.cloud/gpu: "true"
      tolerations:
      - key: yandex.cloud/gpu
        operator: Exists
        effect: NoSchedule
